#!/bin/bash
export LTO_PLUGIN="/usr/local/musl/libexec/gcc/x86_64-linux-musl/8.3.0/liblto_plugin.so.0.0.0"

args=()
for arg in "$@"; do
    args+=("$arg")
done
args+=("--plugin" "${LTO_PLUGIN}")

echo "AR_WRAPPER, RUNNING WITH ARGS: ${args[@]}"

/usr/local/musl/bin/x86_64-linux-musl-ar-real "${args[@]}" 

